MOCK_SERVICES = {
    'service1': {
        'instance1': 'info on instance 1',
        'instance2': 'info on instance 2',
        'instance3': 'info on instance 3',
    },
    'service2': {
        'instance4': 'info on instance4',
        'instance5': 'info on instance5',
        'instance6': 'info on instance6',
        'instance7': 'info on instance7',
        'instance8': 'info on instance8',
        'instance9': 'info on instance9',
        'instance10':
        'info on instance10 BUT REALLY LONG TEXT YOU SHOULD CHECK THAT I CLIP OK\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean lobortis faucibus dignissim. Quisque vitae rhoncus massa, a luctus lorem. Duis vel lobortis nulla. Mauris id ultricies arcu, non fermentum felis. Maecenas fermentum semper turpis ut hendrerit. In pretium massa mattis dapibus vulputate. In scelerisque tincidunt nunc id varius. In egestas, tellus consectetur gravida iaculis, felis nunc sagittis lacus, sit amet efficitur odio felis sed risus. Nulla scelerisque nulla lectus, vel vehicula turpis rutrum ut. Curabitur sit amet sapien lacus. Phasellus efficitur velit a diam faucibus rutrum. Maecenas eget mauris vitae eros mattis faucibus consectetur ornare massa. Nullam eleifend odio maximus diam fringilla tempor. Nunc nunc enim, ullamcorper eget blandit nec, finibus at nunc. Pellentesque eu est eu tellus lacinia feugiat. Cras sed magna vitae purus interdum facilisis.\nVestibulum semper elementum nibh, non cursus quam. Nam nec dapibus urna, dignissim feugiat felis. Nulla a dignissim justo, sed tincidunt dui. Etiam scelerisque, purus et laoreet dignissim, dui tortor facilisis odio, sed faucibus purus eros rutrum dui. Suspendisse molestie pellentesque urna, ultricies bibendum velit sollicitudin pretium. Sed commodo enim purus, eu tempus justo interdum quis. Quisque id imperdiet tortor, nec iaculis eros. Donec quis mi et diam bibendum porttitor. Proin ipsum mi, auctor quis est eget, vehicula faucibus turpis. Nulla eu interdum purus, non aliquam nulla. Etiam nibh est, maximus quis consequat ut, ullamcorper id ligula.\nNulla porttitor nisi nibh, vitae luctus ante auctor at. Donec non congue lorem. Morbi et ultrices mi. Phasellus ut tortor luctus, dapibus sapien vitae, eleifend augue. Etiam molestie a massa ac posuere. Fusce hendrerit, nibh vitae varius aliquet, dui leo ultrices sem, sit amet consequat ante felis quis ante. Suspendisse consequat, arcu ac accumsan dictum, magna dolor iaculis urna, sit amet commodo nibh magna nec lorem. Sed viverra convallis lacus at volutpat. Aliquam a pharetra ligula. Nullam consectetur quam in nibh maximus malesuada. Aliquam leo libero, porta ut hendrerit vel, feugiat et quam. Quisque fermentum imperdiet ligula, nec ultricies tellus malesuada ut. Nullam et ex id odio maximus mollis. Vivamus a odio non mauris scelerisque elementum id nec risus. Curabitur efficitur pellentesque posuere. Phasellus elementum cursus aliquam.\nSed at felis purus. Suspendisse molestie interdum porttitor. Phasellus neque massa, sollicitudin quis lacus non, egestas tristique justo. Nunc at tincidunt erat. Quisque metus lacus, dignissim sit amet gravida ac, pretium nec sapien. Donec egestas placerat augue sed posuere. Praesent imperdiet metus vel justo tincidunt lobortis. Quisque bibendum, est et hendrerit faucibus, arcu leo accumsan velit, sed placerat tortor tortor sed magna. Duis ornare magna ac lacus scelerisque, sit amet blandit nisi elementum.\nFusce semper felis vel odio semper, ac cursus est porttitor. Cras tincidunt ut orci eget porttitor. Sed erat tortor, venenatis eget aliquet consequat, interdum eu eros. Aenean sollicitudin ex lectus, quis placerat dui consectetur quis. Quisque gravida congue metus, consequat molestie lorem aliquam ut. In convallis leo nisl, id ullamcorper libero consectetur congue. Aliquam augue est, convallis at tempor sit amet, dapibus ultrices turpis. Nullam a elit lobortis justo posuere lobortis et vel felis. Donec pretium, purus in pulvinar vulputate, ligula urna convallis tellus, ac mollis lacus justo sed nibh. Aenean viverra, augue et dapibus maximus, lectus augue vestibulum arcu, ut faucibus ex elit eu erat. Aenean ullamcorper dolor id accumsan pretium. Vestibulum imperdiet, nulla at imperdiet eleifend, nunc enim fringilla turpis, at aliquam enim tortor et elit.',
        'instance11': 'info on instance11',
        'instance12': 'info on instance12',
        'instance13': 'info on instance13',
        'instance14': 'info on instance14',
        'instance15': 'info on instance15',
        'instance16': 'info on instance16',
        'instance17': 'info on instance17',
        'instance18': 'info on instance18',
        'instance19': 'info on instance19',
        'instance20': 'info on instance20',
        'instance21': 'info on instance21',
        'instance22': 'info on instance22',
        'instance23': 'info on instance23',
        'instance24': 'info on instance24',
        'instance25': 'info on instance25',
        'instance26': 'info on instance26',
        'instance27': 'info on instance27',
        'instance28': 'info on instance28',
        'instance29': 'info on instance29',
        'instance30': 'info on instance30',
        'instance31': 'info on instance31',
        'instance32': 'info on instance32',
        'instance33': 'info on instance33',
        'instance34': 'info on instance34',
    }
}
